FROM mysql:latest

LABEL AUTHOR="Rafael Yukio Natsu"

ADD ./database/createTable.sql /docker-entrypoint-initdb.d
ADD ./tools/getSiteFile/temp/tornode.clean.sql /docker-entrypoint-initdb.d
ADD ./tools/getSiteFile/temp/onionoo.clean.sql /docker-entrypoint-initdb.d